use indoc::formatdoc;
use std::ffi::OsStr;
use std::io;
use std::process::{Command, Output};
use strum::IntoEnumIterator;
use strum_macros::{Display, EnumString};

use crate::commands;

pub fn execute<T>(cmd: &str, args: T) -> io::Result<Output>
where
    T: IntoIterator,
    T::Item: AsRef<OsStr>,
{
    Command::new(cmd).args(args).output()
}

/// Enum representing supported shell types
#[derive(Debug, Default, Display, Clone, EnumString)]
pub enum Shell {
    #[default]
    #[strum(serialize = "bash")]
    Bash,
    #[strum(serialize = "zsh")]
    Zsh,
    #[strum(serialize = "fish")]
    Fish,
}

pub fn detect() -> Option<Shell> {
    let shell = std::env::var("SHELL").ok()?;
    let shell_name = shell.rsplit('/').next().unwrap_or(shell.as_str());

    match shell_name {
        "zsh" => Some(Shell::Zsh),
        "bash" => Some(Shell::Bash),
        "fish" => Some(Shell::Fish),
        _ => None,
    }
}

/// Generates shell-specific script based on the shell type
pub fn generate_hook(shell: Shell) -> String {
    let binary_name = env!("CARGO_BIN_NAME");
    let mut commands: Vec<String> = commands::Command::iter().map(|c| c.to_string()).collect();

    commands.push("-V".to_string());
    commands.push("--version".to_string());

    commands.push("-h".to_string());
    commands.push("--help".to_string());

    let commands = commands.join("|");

    match shell {
        Shell::Zsh => formatdoc! {r#"
            # Side Project Manager - generated by: {binary_name} init zsh
            function {binary_name}() {{
                if [[ $# -eq 0 ]]; then
                    local dir
                    dir=$(command {binary_name} pick)
                    if [[ $? -eq 0 ]] && [[ -n "$dir" ]]; then
                        cd "$dir"
                    fi
                    return
                fi

                local cmd="$1"
                case "$cmd" in
                    {commands})
                        command {binary_name} "$@"
                        ;;
                    *)
                        local dir
                        dir=$(command {binary_name} pick "$@")
                        if [[ $? -eq 0 ]] && [[ -n "$dir" ]]; then
                            cd "$dir"
                        fi
                        ;;
                esac
            }}
        "#,
        binary_name = binary_name,
        commands = commands
        }
        .to_string(),

        Shell::Bash => formatdoc! {r#"
            # Side Project Manager - generated by: {binary_name} init bash
            function {binary_name}() {{
                if [[ $# -eq 0 ]]; then
                    local dir
                    dir=$(command {binary_name} pick)
                    if [[ $? -eq 0 ]] && [[ -n "$dir" ]]; then
                        cd "$dir"
                    fi
                    return
                fi

                local cmd="$1"
                case "$cmd" in
                    {commands})
                        command {binary_name} "$@"
                        ;;
                    *)
                        local dir
                        dir=$(command {binary_name} pick "$@")
                        if [[ $? -eq 0 ]] && [[ -n "$dir" ]]; then
                            cd "$dir"
                        fi
                        ;;
                esac
            }}
        "#,
        binary_name = binary_name,
        commands = commands
        }
        .to_string(),

        Shell::Fish => formatdoc! {r#"
            # Side Project Manager - generated by: {binary_name} init fish
            function {binary_name} --wraps {binary_name}
                set -l argc (builtin count $argv)

                if test $argc -eq 0
                    if set -l dir (command {binary_name} pick); and test -n "$dir"
                        cd $dir
                    end
                    return
                end

                set -l cmd $argv[1]
                switch $cmd
                    case {commands}
                        command {binary_name} $argv
                    case '*'
                        if set -l dir (command {binary_name} pick $argv); and test -n "$dir"
                            cd $dir
                        end
                end
            end
        "#,
        binary_name = binary_name,
        commands = commands.replace("|", " ")
        }
        .to_string(),
    }
}
